version: '3.1'

services:

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: "P@ssw0rd"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080